Update: Manage to support dual sim: Not tested !
I managed to integrate support for the dual sim. Sms manager can be
retreived for a given number. fall back to default if not found.

Permisson function moved to a helper function: I am really not sure how
to handle this ?

Error when debugin the app on my phone :

```
$ adb shell am start -n
"com.example.stopsmsspam/com.example.stopsmsspam.MainActivity" -a
android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n
"com.example.stopsmsspam/com.example.stopsmsspam.MainActivity" -a
android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN
cat=[android.intent.category.LAUNCHER]
cmp=com.example.stopsmsspam/.MainActivity }
Error type 3
Error: Activity class
{com.example.stopsmsspam/com.example.stopsmsspam.MainActivity} does not
exist.

Error while Launching activity

```
last time I solved it using (this
post)[https://stackoverflow.com/questions/20915266/error-type-3-error-activity-class-does-not-exist]